// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: app/proto/voter.proto

package voter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_app_proto_voter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_voter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_app_proto_voter_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ValidateRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Jwt           string                 `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_app_proto_voter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_voter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_app_proto_voter_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ValidateResponse) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

func (x *ValidateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_app_proto_voter_proto protoreflect.FileDescriptor

const file_app_proto_voter_proto_rawDesc = "" +
	"\n" +
	"\x15app/proto/voter.proto\x12\x05voter\"D\n" +
	"\x0fValidateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"X\n" +
	"\x10ValidateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03jwt\x18\x02 \x01(\tR\x03jwt\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2U\n" +
	"\fVoterService\x12E\n" +
	"\x12ValidateInviteCode\x12\x16.voter.ValidateRequest\x1a\x17.voter.ValidateResponseB\x12Z\x10vote/proto/voterb\x06proto3"

var (
	file_app_proto_voter_proto_rawDescOnce sync.Once
	file_app_proto_voter_proto_rawDescData []byte
)

func file_app_proto_voter_proto_rawDescGZIP() []byte {
	file_app_proto_voter_proto_rawDescOnce.Do(func() {
		file_app_proto_voter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_proto_voter_proto_rawDesc), len(file_app_proto_voter_proto_rawDesc)))
	})
	return file_app_proto_voter_proto_rawDescData
}

var file_app_proto_voter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_proto_voter_proto_goTypes = []any{
	(*ValidateRequest)(nil),  // 0: voter.ValidateRequest
	(*ValidateResponse)(nil), // 1: voter.ValidateResponse
}
var file_app_proto_voter_proto_depIdxs = []int32{
	0, // 0: voter.VoterService.ValidateInviteCode:input_type -> voter.ValidateRequest
	1, // 1: voter.VoterService.ValidateInviteCode:output_type -> voter.ValidateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_proto_voter_proto_init() }
func file_app_proto_voter_proto_init() {
	if File_app_proto_voter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_proto_voter_proto_rawDesc), len(file_app_proto_voter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_proto_voter_proto_goTypes,
		DependencyIndexes: file_app_proto_voter_proto_depIdxs,
		MessageInfos:      file_app_proto_voter_proto_msgTypes,
	}.Build()
	File_app_proto_voter_proto = out.File
	file_app_proto_voter_proto_goTypes = nil
	file_app_proto_voter_proto_depIdxs = nil
}
