// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: app/proto/voter.proto

package voter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VoterService_ValidateInviteCode_FullMethodName = "/voter.VoterService/ValidateInviteCode"
)

// VoterServiceClient is the client API for VoterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VoterService provides RPC methods for validating invite codes and issuing JWTs
type VoterServiceClient interface {
	// ValidateInviteCode validates an invite code and returns a JWT token for authenticated access
	ValidateInviteCode(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type voterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoterServiceClient(cc grpc.ClientConnInterface) VoterServiceClient {
	return &voterServiceClient{cc}
}

func (c *voterServiceClient) ValidateInviteCode(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, VoterService_ValidateInviteCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoterServiceServer is the server API for VoterService service.
// All implementations must embed UnimplementedVoterServiceServer
// for forward compatibility.
//
// VoterService provides RPC methods for validating invite codes and issuing JWTs
type VoterServiceServer interface {
	// ValidateInviteCode validates an invite code and returns a JWT token for authenticated access
	ValidateInviteCode(context.Context, *ValidateRequest) (*ValidateResponse, error)
	mustEmbedUnimplementedVoterServiceServer()
}

// UnimplementedVoterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVoterServiceServer struct{}

func (UnimplementedVoterServiceServer) ValidateInviteCode(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateInviteCode not implemented")
}
func (UnimplementedVoterServiceServer) mustEmbedUnimplementedVoterServiceServer() {}
func (UnimplementedVoterServiceServer) testEmbeddedByValue()                      {}

// UnsafeVoterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoterServiceServer will
// result in compilation errors.
type UnsafeVoterServiceServer interface {
	mustEmbedUnimplementedVoterServiceServer()
}

func RegisterVoterServiceServer(s grpc.ServiceRegistrar, srv VoterServiceServer) {
	// If the following call panics, it indicates UnimplementedVoterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VoterService_ServiceDesc, srv)
}

func _VoterService_ValidateInviteCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoterServiceServer).ValidateInviteCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoterService_ValidateInviteCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoterServiceServer).ValidateInviteCode(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VoterService_ServiceDesc is the grpc.ServiceDesc for VoterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voter.VoterService",
	HandlerType: (*VoterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateInviteCode",
			Handler:    _VoterService_ValidateInviteCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/proto/voter.proto",
}
