type Ballot {
  id: ID!
  invitationId: UInt64!
  pollId: UInt64!
  createdAt: Time!
  updatedAt: Time!
  ballotSelects: [BallotSelect!]!
}

type BallotConnection {
  edges: [BallotEdge!]!
  pageInfo: PageInfo!
  totalCount: Int64!
}

type BallotEdge {
  node: Ballot!
  cursor: ID!
}

input BallotPollOptions {
  pollOptionId: UInt64!
  isSelected: Boolean!
}

input BallotPolls {
  pollId: UInt64!
  pollOptions: [BallotPollOptions!]
}

input BallotCreate {
  selections: [BallotPolls!]!
}

input BallotQuery {
  voteId: UUID!
  pollId: UInt64
  voterId: UInt64
  first: Int64
  after: String
  last: Int64
  before: String
}

extend type Query {
  ballots(input: BallotQuery!): [BallotConnection!]!
    @hasPermission(resource: "ballot", action: "read")
}

extend type Mutation {
  createBallot(input: BallotCreate!): [Ballot!]!
  deleteBallot(VoterId: UInt64!): Boolean!
    @hasPermission(resource: "ballot", action: "delete")
}
