type Candidate {
  id: ID!
  questionId: UInt64!
  name: String!
  result: String!
  createdAt: Time!
  updatedAt: Time!
}

type CandidateConnection {
  edges: [CandidateEdge!]!
  pageInfo: PageInfo!
  totalCount: Int64!
}

type CandidateEdge {
  node: Candidate!
  cursor: ID!
}

input CandidateCreate {
  questionId: UInt64!
  name: String!
}

input CandidateUpdate {
  questionId: UInt64!
  name: String!
}

input CandidateQuery {
  voteId: UUID!
  questionId: UInt64
  name: String
  first: Int64
  after: String
  last: Int64
  before: String
}

extend type Query {
  candidate(id: UInt64!): Candidate!
    @hasPermission(resource: "candidate", action: "read")
  candidates(input: CandidateQuery!): [CandidateConnection!]!
    @hasPermission(resource: "candidate", action: "read")
}

extend type Mutation {
  createCandidate(input: CandidateCreate!): Candidate!
    @hasPermission(resource: "candidate", action: "create")

  updateCandidate(id: UInt64!, input: CandidateUpdate!): Candidate!
    @hasPermission(resource: "candidate", action: "update")

  deleteCandidate(ids: [UInt64!]!): [Candidate!]!
    @hasPermission(resource: "candidate", action: "delete")
}