type Password {
  id: ID!
  voteId: UUID!
  password: String!
  status: Boolean!
  createdAt: Time!
  ballot: [Ballot!]!
}

type PasswordConnection {
  edges: [PasswordEdge!]!
  pageInfo: PageInfo!
  totalCount: Int64!
}

type PasswordEdge {
  node: Password!
  cursor: ID!
}

input PasswordCreate {
  voteId: UUID!
  number: Uint!
  length: Uint!
  format: String!
}

input PasswordUpdate {
  voteId: UUID!
  status: Boolean!
}

input PasswordQuery {
  voteId: UUID!
  password: String
  status: Boolean
  first: Int64
  after: String
  last: Int64
  before: String
}

extend type Query {
  passwords(input: PasswordQuery!): [PasswordConnection!]!
    @hasPermission(resource: "password", action: "read")
}

extend type Mutation {
  createPassword(input: PasswordCreate!): [Password!]!
    @hasPermission(resource: "password", action: "create")

  updatePassword(ids: [UInt64!]!, input: PasswordUpdate!): [Password!]!
    @hasPermission(resource: "password", action: "update")

  deletePassword(ids: [UInt64!]!): [Password!]!
    @hasPermission(resource: "password", action: "delete")
}