// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type PageQuery interface {
	IsPageQuery()
	GetFirst() *int
	GetAfter() *string
	GetLast() *int
	GetBefore() *string
}

type Mutation struct {
}

type Query struct {
}
