package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	model1 "vote/app/model"
	"vote/app/repository"
	"vote/app/service"
	graph "vote/graph/generated"

	"github.com/google/uuid"
)

// CreateBallot is the resolver for the createBallot field.
func (r *mutationResolver) CreateBallot(ctx context.Context, input model1.BallotCreate) ([]*model1.Ballot, error) {
	voterInfo, err := service.NewGraphqlService().GetVoterInfoFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get voter info from context: %v", err)
	}

	if voterInfo.VoterID == 0 {
		return nil, fmt.Errorf("voter ID is missing in context")
	}

	ballots, err := service.NewBallotService().CreateBallots(voterInfo.VoterID, input)
	if err != nil {
		return nil, err
	}
	return ballots, nil
}

// DeleteBallot is the resolver for the deleteBallot field.
func (r *mutationResolver) DeleteBallot(ctx context.Context, voterID uint64) (bool, error) {
	voteId, err := repository.NewInvitationRepository().GetSessionIdByVoterId(voterID)
	if err != nil {
		return false, fmt.Errorf("failed to get vote ID by voter ID: %v", err)
	}

	if err := service.NewAuthorizationService().AuthorizeSessionAccess(ctx, voteId, "delete ballot"); err != nil {
		return false, err
	}

	err = service.NewBallotService().DeleteBallot(voterID)
	if err != nil {
		return false, err
	}

	return true, nil
}

// Ballots is the resolver for the ballots field.
func (r *queryResolver) Ballots(ctx context.Context, input model1.BallotQuery) ([]*model1.BallotConnection, error) {
	if err := service.NewAuthorizationService().AuthorizeSessionAccess(ctx, input.SessionID, "read ballot"); err != nil {
		return nil, err
	}

	ballotConnections, err := service.NewBallotService().GetBallotByVoteId(input)
	if err != nil {
		return nil, err
	}

	return ballotConnections, nil
}

// VoteID is the resolver for the voteId field.
func (r *ballotQueryResolver) VoteID(ctx context.Context, obj *model1.BallotQuery, data uuid.UUID) error {
	panic(fmt.Errorf("not implemented: VoteID - voteId"))
}

// BallotQuery returns graph.BallotQueryResolver implementation.
func (r *Resolver) BallotQuery() graph.BallotQueryResolver { return &ballotQueryResolver{r} }

type ballotQueryResolver struct{ *Resolver }
