package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	model1 "vote/app/model"
	"vote/app/service"
)

// CreateBallot is the resolver for the createBallot field.
func (r *mutationResolver) CreateBallot(ctx context.Context, input model1.BallotCreate) ([]*model1.Ballot, error) {
	voterInfo, err := service.NewGraphqlService().GetUserInfoFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get user info from context: %v", err)
	}

	ballots, err := service.NewBallotService().CreateBallots(voterInfo.UserID, input)
	if err != nil {
		return nil, err
	}
	return ballots, nil
}
