package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"vote/app/model"
	"vote/app/service"
)

// CreateCandidate is the resolver for the createCandidate field.
func (r *mutationResolver) CreateCandidate(ctx context.Context, input model.CandidateCreate) (*model.Candidate, error) {
	bindErr := service.NewGraphqlService().BindQuery(ctx, &input)
	if bindErr != nil {
		return nil, fmt.Errorf("validation error: %s", bindErr.Error())
	}

	userInfo, err := service.NewGraphqlService().GetUserInfoFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get user info from context: %v", err)
	}

	candidate, err := service.NewCandidateService().CreateCandidate(userInfo, input)
	if err != nil {
		return nil, err
	}
	return candidate, nil
}

// UpdateCandidate is the resolver for the updateCandidate field.
func (r *mutationResolver) UpdateCandidate(ctx context.Context, id uint64, input model.CandidateUpdate) (*model.Candidate, error) {
	bindErr := service.NewGraphqlService().BindQuery(ctx, &input)
	if bindErr != nil {
		return nil, fmt.Errorf("validation error: %s", bindErr.Error())
	}

	userInfo, err := service.NewGraphqlService().GetUserInfoFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get user info from context: %v", err)
	}

	candidate, err := service.NewCandidateService().UpdateCandidate(userInfo, id, input)
	if err != nil {
		return nil, err
	}
	return candidate, nil
}

// DeleteCandidate is the resolver for the deleteCandidate field.
func (r *mutationResolver) DeleteCandidate(ctx context.Context, ids []uint64) ([]*model.Candidate, error) {
	userInfo, err := service.NewGraphqlService().GetUserInfoFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get user info from context: %v", err)
	}

	candidates, err := service.NewCandidateService().DeleteCandidate(ids, userInfo)
	if err != nil {
		return nil, err
	}
	return candidates, nil
}

// Candidate is the resolver for the candidate field.
func (r *queryResolver) Candidate(ctx context.Context, id uint64) (*model.Candidate, error) {
	userInfo, err := service.NewGraphqlService().GetUserInfoFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get user info from context: %v", err)
	}

	candidate, err := service.NewCandidateService().GetCandidate(id, userInfo.IsAdmin, userInfo.UserID)
	if err != nil {
		return nil, err
	}

	return candidate, nil
}

// Candidates is the resolver for the candidates field.
func (r *queryResolver) Candidates(ctx context.Context, input model.CandidateQuery) ([]*model.CandidateConnection, error) {
	if err := service.NewAuthorizationService().AuthorizeVoteAccess(ctx, input.VoteID, "read candidate"); err != nil {
		return nil, err
	}

	candidateConnections, err := service.NewCandidateService().GetCandidates(&input)

	if err != nil {
		return nil, err
	}

	return candidateConnections, nil
}
