package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"vote/app/model"
	pb "vote/proto/voter"
	"vote/app/service"
	"vote/app/utils"
	graph "vote/graph/generated"
	"vote/internal/grpcclient"

	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Ballot is the resolver for the ballot field.
func (r *invitationResolver) Ballot(ctx context.Context, obj *model.Invitation) ([]*model.Ballot, error) {
	panic(fmt.Errorf("not implemented: Ballot - ballot"))
}

// CreateInvitation is the resolver for the createInvitation field.
func (r *mutationResolver) CreateInvitation(ctx context.Context, input model.InvitationCreate) ([]*model.Invitation, error) {
	if err := service.NewAuthorizationService().AuthorizeSessionAccess(ctx, input.SessionID, "create invitation"); err != nil {
		return nil, err
	}

	bindErr := service.NewGraphqlService().BindQuery(ctx, &input)
	if bindErr == nil {
		invitations, err := service.NewInvitationService().CreateInvitation(input.SessionID, input.Number, input.Length, input.Format)
		if err != nil {
			return nil, err
		}
		return invitations, nil
	}

	return nil, gqlerror.Errorf("%s", utils.ValidationErrorMessage(bindErr))
}

// UpdateInvitation is the resolver for the updateInvitation field.
func (r *mutationResolver) UpdateInvitation(ctx context.Context, ids []uint64, input model.InvitationUpdate) ([]*model.Invitation, error) {
	if err := service.NewAuthorizationService().AuthorizeSessionAccess(ctx, input.SessionID, "update invitation"); err != nil {
		return nil, err
	}

	bindErr := service.NewGraphqlService().BindQuery(ctx, &input)
	if bindErr == nil {
		invitations, err := service.NewInvitationService().UpdateInvitationStatus(input.SessionID, ids, input.Status)
		if err != nil {
			return nil, err
		}
		return invitations, nil
	}

	return nil, gqlerror.Errorf("%s", utils.ValidationErrorMessage(bindErr))
}

// DeleteInvitation is the resolver for the deleteInvitation field.
func (r *mutationResolver) DeleteInvitation(ctx context.Context, ids []uint64) ([]*model.Invitation, error) {
	userInfo, err := service.NewGraphqlService().GetUserInfoFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get user info from context: %v", err)
	}

	invitations, err := service.NewInvitationService().DeleteInvitation(ids, userInfo)
	if err != nil {
		return nil, err
	}
	return invitations, nil
}

// ValidateInviteCode is the resolver for the validateInviteCode field.
func (r *mutationResolver) ValidateInviteCode(ctx context.Context, sessionID string, code string) (*model.ValidateInviteResult, error) {
	client := grpcclient.GetVoterServiceClient()

	response, err := client.ValidateInviteCode(ctx, &pb.ValidateRequest{
		SessionId: sessionID,
		Code:      code,
	})

	if err != nil {
		return nil, fmt.Errorf("failed to validate invite code: %w", err)
	}

	if !response.Success {
		return &model.ValidateInviteResult{
			Success: false,
			Message: response.Message,
		}, nil
	}

	return &model.ValidateInviteResult{
		Success: true,
		JWT:     response.Jwt,
		Message: response.Message,
	}, nil
}

// Invitations is the resolver for the invitations field.
func (r *queryResolver) Invitations(ctx context.Context, input model.InvitationQuery) ([]*model.InvitationConnection, error) {
	if err := service.NewAuthorizationService().AuthorizeSessionAccess(ctx, input.SessionID, "read invitation"); err != nil {
		return nil, err
	}

	bindErr := service.NewGraphqlService().BindQuery(ctx, &input)
	if bindErr == nil {
		invitations, err := service.NewInvitationService().GetInvitations(input.SessionID, &input)
		if err != nil {
			return nil, err
		}
		return invitations, nil
	}

	return nil, gqlerror.Errorf("%s", utils.ValidationErrorMessage(bindErr))
}

// DecryptInvitation is the resolver for the decryptInvitation field.
func (r *queryResolver) DecryptInvitation(ctx context.Context, codeHash string) (string, error) {
	decryptedInvitation, err := service.NewInvitationService().DecryptInvitation(codeHash)
	if err != nil {
		return "", fmt.Errorf("failed to decrypt invitation: %w", err)
	}

	return decryptedInvitation, nil
}

// Number is the resolver for the number field.
func (r *invitationCreateResolver) Number(ctx context.Context, obj *model.InvitationCreate, data uint32) error {
	obj.Number = uint(data)
	return nil
}

// Length is the resolver for the length field.
func (r *invitationCreateResolver) Length(ctx context.Context, obj *model.InvitationCreate, data uint32) error {
	obj.Length = uint(data)
	return nil
}

// Invitation returns graph.InvitationResolver implementation.
func (r *Resolver) Invitation() graph.InvitationResolver { return &invitationResolver{r} }

// InvitationCreate returns graph.InvitationCreateResolver implementation.
func (r *Resolver) InvitationCreate() graph.InvitationCreateResolver {
	return &invitationCreateResolver{r}
}

type invitationResolver struct{ *Resolver }
type invitationCreateResolver struct{ *Resolver }
