package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"vote/app/model"
	graph "vote/graph/generated"
)

// Ballot is the resolver for the ballot field.
func (r *passwordResolver) Ballot(ctx context.Context, obj *model.Password) ([]*model.Ballot, error) {
	panic(fmt.Errorf("not implemented: Ballot - ballot"))
}

// Password returns graph.PasswordResolver implementation.
func (r *Resolver) Password() graph.PasswordResolver { return &passwordResolver{r} }

type passwordResolver struct{ *Resolver }
