package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"vote/app/model"
	"vote/app/service"
	"vote/app/utils"

	"github.com/google/uuid"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreatePoll is the resolver for the createPoll field.
func (r *mutationResolver) CreatePoll(ctx context.Context, input model.PollCreate) (*model.Poll, error) {
	if err := service.NewAuthorizationService().AuthorizeSessionAccess(ctx, input.SessionID, "create poll"); err != nil {
		return nil, err
	}

	bindErr := service.NewGraphqlService().BindQuery(ctx, &input)
	if bindErr == nil {
		poll, err := service.NewPollService().CreatePoll(input)
		if err != nil {
			return nil, err
		}
		return poll, nil
	}

	return nil, gqlerror.Errorf("%s", utils.ValidationErrorMessage(bindErr))
}

// UpdatePoll is the resolver for the updatePoll field.
func (r *mutationResolver) UpdatePoll(ctx context.Context, id uint64, input model.PollUpdate) (*model.Poll, error) {
	if err := service.NewAuthorizationService().AuthorizeSessionAccess(ctx, input.SessionID, "update poll"); err != nil {
		return nil, err
	}

	bindErr := service.NewGraphqlService().BindQuery(ctx, &input)
	if bindErr == nil {
		poll, err := service.NewPollService().UpdatePoll(id, input)
		if err != nil {
			return nil, err
		}
		return poll, nil
	}

	return nil, gqlerror.Errorf("%s", utils.ValidationErrorMessage(bindErr))
}

// DeletePoll is the resolver for the deletePoll field.
func (r *mutationResolver) DeletePoll(ctx context.Context, ids []uint64) ([]*model.Poll, error) {
	userInfo, err := service.NewGraphqlService().GetUserInfoFromContext(ctx)
	if err != nil {
		return nil, gqlerror.Errorf("failed to get user info from context: %v", err)
	}

	polls, err := service.NewPollService().DeletePoll(ids, userInfo)
	if err != nil {
		return nil, gqlerror.Errorf("failed to delete polls: %v", err)
	}

	return polls, nil
}

// Poll is the resolver for the poll field.
func (r *queryResolver) Poll(ctx context.Context, id uint64, withPollOptions bool) (*model.Poll, error) {
	userInfo, err := service.NewGraphqlService().GetUserInfoFromContext(ctx)
	if err != nil {
		return nil, err
	}

	if withPollOptions {
		return service.NewPollService().SelectPollWithPollOptions(id, userInfo.IsAdmin, userInfo.UserID)
	}

	return service.NewPollService().GetPoll(id, userInfo.IsAdmin, userInfo.UserID)
}

// Polls is the resolver for the polls field.
func (r *queryResolver) Polls(ctx context.Context, input model.PollQuery, withPollOptions bool) ([]*model.PollConnection, error) {
	if err := service.NewAuthorizationService().AuthorizeSessionAccess(ctx, input.SessionID, "read poll"); err != nil {
		return nil, err
	}

	input.PollOptions = withPollOptions
	pollConnections, err := service.NewPollService().GetPolls(&input)

	if err != nil {
		return nil, err
	}

	return pollConnections, nil
}

// PollList is the resolver for the pollList field.
func (r *queryResolver) PollList(ctx context.Context, sessionID uuid.UUID) (*model.PollList, error) {
	if err := service.NewAuthorizationService().AuthorizeSessionAccess(ctx, sessionID, "read poll"); err != nil {
		return nil, err
	}

	polls, err := service.NewPollService().GetPollList(sessionID)
	if err != nil {
		return nil, err
	}

	return polls, nil
}
