package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"vote/app/model"
	"vote/app/service"
)

// CreatePollOption is the resolver for the createPollOption field.
func (r *mutationResolver) CreatePollOption(ctx context.Context, input model.PollOptionCreate) (*model.PollOption, error) {
	bindErr := service.NewGraphqlService().BindQuery(ctx, &input)
	if bindErr != nil {
		return nil, fmt.Errorf("validation error: %s", bindErr.Error())
	}

	userInfo, err := service.NewGraphqlService().GetUserInfoFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get user info from context: %v", err)
	}

	pollOption, err := service.NewPollOptionService().CreatePollOption(userInfo, input)
	if err != nil {
		return nil, err
	}
	return pollOption, nil
}

// UpdatePollOption is the resolver for the updatePollOption field.
func (r *mutationResolver) UpdatePollOption(ctx context.Context, id uint64, input model.PollOptionUpdate) (*model.PollOption, error) {
	bindErr := service.NewGraphqlService().BindQuery(ctx, &input)
	if bindErr != nil {
		return nil, fmt.Errorf("validation error: %s", bindErr.Error())
	}

	userInfo, err := service.NewGraphqlService().GetUserInfoFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get user info from context: %v", err)
	}

	pollOption, err := service.NewPollOptionService().UpdatePollOption(userInfo, id, input)
	if err != nil {
		return nil, err
	}
	return pollOption, nil
}

// DeletePollOption is the resolver for the deletePollOption field.
func (r *mutationResolver) DeletePollOption(ctx context.Context, ids []uint64) ([]*model.PollOption, error) {
	userInfo, err := service.NewGraphqlService().GetUserInfoFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get user info from context: %v", err)
	}

	pollOptions, err := service.NewPollOptionService().DeletePollOption(ids, userInfo)
	if err != nil {
		return nil, err
	}
	return pollOptions, nil
}

// PollOption is the resolver for the pollOption field.
func (r *queryResolver) PollOption(ctx context.Context, id uint64) (*model.PollOption, error) {
	userInfo, err := service.NewGraphqlService().GetUserInfoFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get user info from context: %v", err)
	}

	pollOption, err := service.NewPollOptionService().GetPollOption(id, userInfo.IsAdmin, userInfo.UserID)
	if err != nil {
		return nil, err
	}

	return pollOption, nil
}

// PollOptions is the resolver for the pollOptions field.
func (r *queryResolver) PollOptions(ctx context.Context, input model.PollOptionQuery) ([]*model.PollOptionConnection, error) {
	if err := service.NewAuthorizationService().AuthorizeSessionAccess(ctx, input.SessionID, "read poll option"); err != nil {
		return nil, err
	}

	pollOptionConnections, err := service.NewPollOptionService().GetPollOptions(&input)

	if err != nil {
		return nil, err
	}

	return pollOptionConnections, nil
}
