package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"vote/app/model"
	"vote/app/service"

	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateQuestion is the resolver for the createQuestion field.
func (r *mutationResolver) CreateQuestion(ctx context.Context, input model.QuestionCreate) (*model.Question, error) {
	question, err := service.NewQuestionService().CreateQuestion(input)
	if err != nil {
		return nil, err
	}
	return question, nil
}

// Questions is the resolver for the questions field.
func (r *queryResolver) Questions(ctx context.Context, input *model.QuestionQuery, withCandidates bool) ([]*model.QuestionConnection, error) {
	userId, isAdmin, err := service.NewGraphqlService().GetUserInfoFromContext(ctx)
	if err != nil {
		return nil, gqlerror.Errorf("failed to get user info from context: %v", err)
	}

	input.Candidates = withCandidates
	questionConnections, err := service.NewQuestionService().GetQuestions(isAdmin, userId, input)

	if err != nil {
		return nil, err
	}

	return questionConnections, nil
}
