package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"vote/app/model"
	"vote/app/service"
	graph "vote/graph/generated"

	"github.com/google/uuid"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateSession is the resolver for the createSession field.
func (r *mutationResolver) CreateSession(ctx context.Context, input model.SessionCreate) (*model.Session, error) {
	userInfo, err := service.NewGraphqlService().GetUserIdFromContext(ctx)
	if err != nil {
		return nil, gqlerror.Errorf("user not exists")
	}

	input.UserID = userInfo.UserID

	session, err := service.NewSessionService().CreateSession(input)
	if err != nil {
		return nil, gqlerror.Errorf("failed to create session: %v", err)
	}

	return session, nil
}

// UpdateSession is the resolver for the updateSession field.
func (r *mutationResolver) UpdateSession(ctx context.Context, uuid uuid.UUID, input model.SessionUpdate) (*model.Session, error) {
	if err := service.NewAuthorizationService().AuthorizeSessionAccess(ctx, uuid, "update session"); err != nil {
		return nil, err
	}

	session, err := service.NewSessionService().UpdateSession(uuid, input)
	if err != nil {
		return nil, err
	}

	return session, nil
}

// DeleteSession is the resolver for the deleteSession field.
func (r *mutationResolver) DeleteSession(ctx context.Context, uuids []uuid.UUID) ([]*model.Session, error) {
	if err := service.NewAuthorizationService().AuthorizeSessionAccess(ctx, uuids, "delete session"); err != nil {
		return nil, err
	}

	sessions, err := service.NewSessionService().DeleteSession(uuids)
	if err != nil {
		return nil, gqlerror.Errorf("failed to delete sessions: %v", err)
	}

	return sessions, nil
}

// Session is the resolver for the session field.
func (r *queryResolver) Session(ctx context.Context, uuid *uuid.UUID, withPolls bool) (*model.Session, error) {
	if err := service.NewAuthorizationService().AuthorizeSessionAccess(ctx, uuid, "read session"); err != nil {
		return nil, err
	}

	session, err := service.NewSessionService().GetSession(*uuid)

	return session, err
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context, input *model.SessionQuery, withPolls bool) ([]*model.SessionConnection, error) {
	userInfo, err := service.NewGraphqlService().GetUserInfoFromContext(ctx)
	if err != nil {
		return nil, err
	}

	sessions, err := service.NewSessionService().GetSessions(userInfo, input)

	return sessions, err
}

// Creator is the resolver for the creator field.
func (r *sessionResolver) Creator(ctx context.Context, obj *model.Session) (*model.User, error) {
	user, err := service.NewUserService().GetUserById(obj.UserID)

	return user, err
}

// Session returns graph.SessionResolver implementation.
func (r *Resolver) Session() graph.SessionResolver { return &sessionResolver{r} }

type sessionResolver struct{ *Resolver }
