package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"vote/app/model"
	"vote/app/service"
	graph "vote/graph/generated"

	"github.com/google/uuid"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateVote is the resolver for the createVote field.
func (r *mutationResolver) CreateVote(ctx context.Context, input model.VoteCreate) (*model.Vote, error) {
	userId, err := service.NewGraphqlService().GetUserIdFromContext(ctx)
	if err != nil {
		return nil, gqlerror.Errorf("user not exists")
	}

	input.UserID = userId

	vote, err := service.NewVoteService().CreateVote(input)
	if err != nil {
		return nil, gqlerror.Errorf("failed to create vote: %v", err)
	}

	return vote, nil
}

// UpdateVote is the resolver for the updateVote field.
func (r *mutationResolver) UpdateVote(ctx context.Context, uuid uuid.UUID, input model.VoteUpdate) (*model.Vote, error) {
	vote, err := service.NewVoteService().UpdateVote(uuid, input)
	if err != nil {
		return nil, err
	}

	return vote, nil
}

// DeleteVote is the resolver for the deleteVote field.
func (r *mutationResolver) DeleteVote(ctx context.Context, uuids []uuid.UUID) ([]*model.Vote, error) {
	userId, isAdmin, err := service.NewGraphqlService().GetUserInfoFromContext(ctx)
	if err != nil {
		return nil, err
	}

	votes, err := service.NewVoteService().DeleteVote(uuids, isAdmin, userId)
	if err != nil {
		return nil, gqlerror.Errorf("failed to delete votes: %v", err)
	}

	return votes, nil
}

// Votes is the resolver for the votes field.
func (r *queryResolver) Votes(ctx context.Context, input *model.VoteQuery, withQuestions bool) ([]*model.VoteConnection, error) {
	userId, isAdmin, err := service.NewGraphqlService().GetUserInfoFromContext(ctx)
	if err != nil {
		return nil, err
	}

	votes, err := service.NewVoteService().GetVotes(isAdmin, userId, input)

	return votes, err
}

// Creator is the resolver for the creator field.
func (r *voteResolver) Creator(ctx context.Context, obj *model.Vote) (*model.User, error) {
	user, err := service.NewUserService().GetUserById(int64(obj.UserID))

	return user, err
}

// Vote returns graph.VoteResolver implementation.
func (r *Resolver) Vote() graph.VoteResolver { return &voteResolver{r} }

type voteResolver struct{ *Resolver }
